import type { GeneratedAccModule } from '@midnight-ntwrk/mn-passport-adapter-browser';
// The generated module, synced into src/acc/generated by scripts/sync-acc.mjs and mapped to `#acc`
// in package.json "imports". It must sit inside the workspace so that its compact-runtime import
// resolves the copy midnight-js uses (the script explains the two-copies failure).
import { Contract, ledger, pureCircuits } from '#acc';

export const accModule: GeneratedAccModule = { Contract, ledger, pureCircuits };
